- name: Provision Linode Server and Deploy Docker Container
  hosts: linode
  become: true  # Run tasks with sudo privileges
  pre_tasks:
    - name: Install community.docker collection
      ansible.builtin.command:
        cmd: ansible-galaxy collection install community.docker
      when: ansible_version.full is version('2.10', '>=')

  tasks:
    # Update and upgrade all packages
    - name: Update and upgrade all packages
      apt:
        update_cache: yes
        upgrade: dist

    # Ensure essential packages are installed
    - name: Ensure essential packages are installed
      apt:
        name:
          - curl
          - git
          - unzip
          - software-properties-common
        state: present

    # Block for Docker installation and service management
    - block:
        - name: Check if Docker is installed
          command: docker --version
          register: docker_check
          ignore_errors: yes

        - name: Install Docker if not installed
          apt:
            name: docker.io
            state: present
          when: docker_check.failed

        - name: Start and enable Docker service
          systemd:
            name: docker
            state: started
            enabled: yes

    # Docker login to Docker Hub
    - name: Log into Docker Hub
      community.docker.docker_login:
        username: "{{ lookup('env', 'DOCKER_USERNAME') }}"
        password: "{{ lookup('env', 'DOCKER_PASSWORD') }}"

    # Pull the Docker image from Docker Hub
    - name: Pull Docker image from Docker Hub
      community.docker.docker_image:
        name: "{{ image_tag }}"  # The image_tag is passed from GitHub Actions as an extra var
        source: pull

    # Run the Docker container
    - name: Run Docker container
      community.docker.docker_container:
        name: easydrive
        image: "{{ image_tag }}"
        state: started
        restart_policy: always
        published_ports:
          - "80:80"  # Map container port 80 to host port 80 (change as necessary)

  handlers:
    # No need to reload Nginx as we are not configuring Nginx in this playbook
