---
- name: Provision Linode Server and Deploy Docker Container
  hosts: "{{ linode_host | default('localhost') }}"
  become: true  # Run tasks with sudo privileges
  pre_tasks:
    - name: Install community.docker collection
      ansible.builtin.command:
        cmd: ansible-galaxy collection install community.docker
      when: ansible_version.full is version('2.10', '>=')

  tasks:
    - name: Update and upgrade all packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist

    - name: Ensure essential packages are installed
      ansible.builtin.apt:
        name:
          - curl
          - git
          - unzip
          - software-properties-common
        state: present

    - block:
        - name: Check if Docker is installed
          ansible.builtin.command:
            cmd: docker --version
          register: docker_check
          ignore_errors: yes
          changed_when: false

        - name: Install Docker if not installed
          ansible.builtin.apt:
            name: docker.io
            state: present
          when: "'docker' not in docker_check.stdout"

        - name: Start and enable Docker service
          ansible.builtin.systemd:
            name: docker
            state: started
            enabled: yes

    - name: Log into Docker Hub
      community.docker.docker_login:
        username: "{{ lookup('env', 'DOCKER_USERNAME') }}"
        password: "{{ lookup('env', 'DOCKER_PASSWORD') }}"
      no_log: true

    - name: Pull Docker image from Docker Hub
      community.docker.docker_image:
        name: "{{ image_tag }}"
        source: pull

    - name: Run Docker container
      community.docker.docker_container:
        name: easydrive
        image: "{{ image_tag }}"
        state: started
        restart_policy: always
        published_ports:
          - "80:80"
  handlers:
    - name: Start Docker service
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes
