---
- name: Provision Linode Server and Deploy Docker Container
  hosts: linode  # The group defined in your inventory file
  become: true  # Run tasks with sudo privileges

  tasks:
    - name: Update and upgrade all packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist

    - name: Ensure essential packages are installed
      ansible.builtin.apt:
        name:
          - curl
          - git
          - unzip
          - software-properties-common
        state: present

    - block:
        - name: Check if Docker is installed
          ansible.builtin.command:
            cmd: docker --version
          register: docker_check
          ignore_errors: yes
          changed_when: false

        - name: Install Docker if not installed
          ansible.builtin.apt:
            name: docker.io
            state: present
          when: "'docker' not in docker_check.stdout"

        - name: Start and enable Docker service
          ansible.builtin.systemd:
            name: docker
            state: started
            enabled: yes

    - name: Log into Docker Hub
      community.docker.docker_login:
        username: "{{ lookup('env', 'DOCKER_USERNAME') }}"
        password: "{{ lookup('env', 'DOCKER_PASSWORD') }}"
      no_log: true

    - name: Pull Docker image from Docker Hub
      community.docker.docker_image:
        name: "{{ image_tag }}"  # Replace with your image tag (e.g., 'myimage:latest')
        source: pull

    - name: Run Docker container
      community.docker.docker_container:
        name: easydrive  # Name of the container
        image: "{{ image_tag }}"  # Use the image pulled from Docker Hub
        state: started
        restart_policy: always
        published_ports:
          - "80:80"  # Example port mapping

