name: Provision Linode Server and Deploy Docker Container

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python and install dependencies
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Ansible and Required Collections
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint
          ansible-galaxy collection install community.docker

      # Step 3: Add the SSH private key to the SSH agent
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H YOUR_LINODE_IP >> ~/.ssh/known_hosts  # Replace with your Linode IP
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 4: Validate Ansible Playbook Syntax
      - name: Validate Ansible Playbook Syntax
        run: ansible-playbook --syntax-check provision.yml

      # Step 5: Run Ansible Playbook
      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/inventory ansible/provision.yml
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
